#!/bin/bash
clear
chk=$(cat /etc/ssh/sshd_config | grep Banner)
[[ $(netstat -nltp|grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >>  /etc/default/dropbear
}
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
    local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}
echo -e "\E[44;1;37m             BANNER             \E[0m"
echo ""
echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;37m • \033[1;33mADD BANNER"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;37m • \033[1;33mREMOVE BANNER"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;37m • \033[1;33mBACK"
echo ""
echo -ne "\033[1;32mWHAT DO YOU WANT TO DO\033[1;31m ?\033[1;37m : "; read resp
if [[ "$resp" = "1" ]]; then
echo ""
echo -ne "\033[1;32mWHAT MESSAGE DO YOU WANT TO DISPLAY\033[1;31m ?\033[1;37m : "; read msg1
if [[ -z "$msg1" ]]; then
    echo -e "\n\033[1;31mEmpty or invalid field!\033[0m"
    sleep 2
    banner
fi
echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m SMALL FONT"
echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m MEDIUM FONT"
echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m LARGE FONT"
echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m GIANT FONT"
echo ""
echo -ne "\033[1;32mWHAT FONT SIZE\033[1;31m ?\033[1;37m : "; read opc
if [[ "$opc" = "1" ]] || [[ "$opc" = "01" ]]; then
_size='6'
elif [[ "$opc" = "2" ]] || [[ "$opc" = "02" ]]; then
_size='4'
elif [[ "$opc" = "3" ]] || [[ "$opc" = "03" ]]; then
_size='3'
elif [[ "$opc" = "4" ]] || [[ "$opc" = "04" ]]; then
_size='1'
fi

echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m BLUE"
echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m GREEN"
echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m RED"
echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m YELLOW"
echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m PINK"
echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYAN"
echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m ORANGE"
echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m PURPLE"
echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m BLACK"
echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m NO COLOR"
echo ""
echo -ne "\033[1;32mWHAT COLOR\033[1;31m ?\033[1;37m : "; read ban_cor
if [[ "$ban_cor" = "1" ]] || [[ "$ban_cor" = "01" ]]; then
echo "<h$_size><font color='blue'>$msg1" >> $local
elif [[ "$ban_cor" = "2" ]] || [[ "$ban_cor" = "02" ]]; then
echo "<h$_size><font color='green'>$msg1" >> $local
elif [[ "$ban_cor" = "3" ]] || [[ "$ban_cor" = "03" ]]; then
echo "<h$_size><font color='red'>$msg1" >> $local
elif [[ "$ban_cor" = "4" ]] || [[ "$ban_cor" = "04" ]]; then
echo "<h$_size><font color='yellow'>$msg1" >> $local
elif [[ "$ban_cor" = "5" ]] || [[ "$ban_cor" = "05" ]]; then
echo "<h$_size><font color='#F535AA'>$msg1" >> $local
elif [[ "$ban_cor" = "6" ]] || [[ "$ban_cor" = "06" ]]; then
echo "<h$_size><font color='cyan'>$msg1" >> $local
elif [[ "$ban_cor" = "7" ]] || [[ "$ban_cor" = "07" ]]; then
echo "<h$_size><font color='#FF7F00'>$msg1" >> $local
elif [[ "$ban_cor" = "8" ]] || [[ "$ban_cor" = "08" ]]; then
echo "<h$_size><font color='#9932CD'>$msg1" >> $local
elif [[ "$ban_cor" = "9" ]] || [[ "$ban_cor" = "09" ]]; then
echo "<h$_size><font color='black'>$msg1" >> $local
elif [[ "$ban_cor" = "10" ]]; then
echo "<h$_size>$msg1</h$_size>" >> $local
/etc/init.d/ssh restart > /dev/null 2>&1
echo -e "\n\033[1;32mBANNER SET!\033[0m"
sleep 2
menu
else
echo -e "\n\033[1;31mInvalid option!\033[0m"
    sleep 2
    banner
fi
echo "</font></h$_size>" >> $local
service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
echo -e "\n\033[1;32mBANNER SET!\033[0m"
unset ban_cor
elif [[ "$resp" = "2" ]]; then
    echo " " > $local
    echo -e "\n\033[1;32mBANNER REMOVED!\033[0m"
    service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
    sleep 2
    menu
elif [[ "$resp" = "3" ]]; then
    menu
else
    echo -e "\n\033[_{{{CITATION{{{_1{](https://github.com/binnh2002/sshpanel/tree/ede3a5dfb9c518383ce68ce2548ebf3eafb15a47/_$_Version%2FSSHPLUS%20v24%2FModulos%2Fbanner.sh)[_{{{CITATION{{{_2{](https://github.com/joker41pro/VPS-JOKER/tree/ac81faa623295e065b19fb84a14f6756c1922b2a/Modulos%2Fbanner.sh)[_{{{CITATION{{{_3{](https://github.com/RolkosModai/SSHPLUSeng/tree/3733cd413e9d75d51409bec9713113e28f6f4a98/Modulos%2Fbanner.sh)[_{{{CITATION{{{_4{](https://github.com/shashikacine/cj-ssh-server-vip/tree/ebbdab3e4910e30accc2531b4d3c5499d694b8f6/Modulos%2Fbanner.sh)[_{{{CITATION{{{_5{](https://github.com/bhoeyong/autoscript4/tree/7211ec5e0e9184d948281ed0715bb1d5182d5619/banner1.sh)[_{{{CITATION{{{_6{](https://github.com/joker41pro/VPS-JOKER/tree/ac81faa623295e065b19fb84a14f6756c1922b2a/Modulos%2Fconexao.sh)[_{{{CITATION{{{_7{](https://github.com/ko2x/VPSEG/tree/76064e3b43f69ec87ffdfaf90733e7f2e21c905c/Modulos%2Fconexao.sh)
